[package]
name = "prudent"
version = "0.0.3-beta"
edition = "2018"

license = "BSD-2-Clause OR Apache-2.0 OR MIT"

# rust-version is recognized only since Rust 1.56, but that's OK.
#
# Tests require Rust 1.79+
rust-version = "1.39"

authors = ["Peter Lyons Kehl<peter.kehl@gmail.com>"]
description = "Help you make Rust code safer. For both authors and reviewers."

categories = ["development-tools", "no-std", "no-std::no-alloc", "rust-patterns", "security"]

keywords = ["safe", "safety", "unsafe", "isolation", "review"]

repository = "https://github.com/prudent-rs/prudent"
homepage = "https://github.com/prudent-rs/prudent"

[lints.rust]
unexpected_cfgs = { level = "forbid"}
