# - KEEP this in sync with ../../test.sh
# - BUT, ../../test.sh needs to undo any effects of directory change (`cd`), while here each GitHub action step starts
#   in the repository directory

name: Tests, doc tests, MIRI, violations coverage

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    # Cargo.toml has "rust-version" (MSRV) 1.31. But, 1.37 is the oldest Alpine docker image. See
    # https://hub.docker.com/_/rust/tags?name=alpine&ordering=-last_updated.
    #
    # rust:1.37-alpine was failing some GitHub's extra checks:
    # https://github.com/peter-lyons-kehl/prudent/actions/runs/18773758118/job/53563574851
    #
    # Other Rust Alpine images that I've tried and they failed: rust:1.54.0-alpine.
    #
    # Also, our tests use usize::unchecked_add, which was stabilized in Rust 1.79.
    #
    # However, with Rust 1.88.0 or older, we were getting false positive errors from `cargo test`,
    # reporting constants in doctests as unused, even though they were used. That's why we need at
    # least 1.89.
    container: rust:1.89.0-alpine
    # TODO rust:1.93-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: rustup components
        shell: sh
        run: |
          rustup component add clippy rustfmt
          rustup install nightly --profile minimal
          rustup +nightly component add miri
          # violations_coverage/verify_error_messages uses trybuild, which uses Serde (a proc
          # macro), which needs to be run as a dynamic library, so it needs musl-dev
          apk add --no-cache musl-dev

      - name: test.sh
        shell: sh
        run: ./test.sh
